# Generated by Django 5.2.8 on 2025-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ 1'), (2, '⭐⭐ 2'), (3, '⭐⭐⭐ 3'), (4, '⭐⭐⭐⭐ 4'), (5, '⭐⭐⭐⭐⭐ 5')], default=5),
        ),
    ]
