# Generated by Django 5.2.8 on 2025-11-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comment_file_alter_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='file',
            new_name='image',
        ),
    ]
